# Typo check: https://github.com/crate-ci/typos

[files]
extend-exclude = ["*.json", "*.js", "static/*", "layouts/*", "assets/*", "i18n/*"]

[default]
extend-ignore-re = [
    "mmaping files"
]

[default.extend-words]
datas = "datas"
mmaped = "mmaped"
exten = "exten"
invokable = "invokable"
typ = "typ"
Rabit = "Rabit"
